"""ISO 3166-1 alpha-3 lookup tables for source-specific country name spellings.

EI Statistical Review and GEM use slightly different country name spellings,
so we keep two separate dicts. Future sources can add their own.
"""

from __future__ import annotations

# Energy Institute Statistical Review (panel + wide sheets)
EI_NAME_TO_ISO3: dict[str, str] = {
    # North America
    "Canada": "CAN",
    "Mexico": "MEX",
    "US": "USA",
    # South & Central America
    "Argentina": "ARG",
    "Brazil": "BRA",
    "Colombia": "COL",
    "Ecuador": "ECU",
    "Guyana": "GUY",
    "Peru": "PER",
    "Trinidad & Tobago": "TTO",
    "Venezuela": "VEN",
    # Europe
    "Denmark": "DNK",
    "Italy": "ITA",
    "Norway": "NOR",
    "Romania": "ROU",
    "United Kingdom": "GBR",
    # CIS / Former USSR
    "Azerbaijan": "AZE",
    "Kazakhstan": "KAZ",
    "Russian Federation": "RUS",
    "Turkmenistan": "TKM",
    "Uzbekistan": "UZB",
    # Middle East
    "Iran": "IRN",
    "Iraq": "IRQ",
    "Kuwait": "KWT",
    "Oman": "OMN",
    "Qatar": "QAT",
    "Saudi Arabia": "SAU",
    "Syria": "SYR",
    "United Arab Emirates": "ARE",
    "Yemen": "YEM",
    # Africa
    "Algeria": "DZA",
    "Angola": "AGO",
    "Chad": "TCD",
    "Republic of Congo": "COG",
    "Republic of Congo ": "COG",  # trailing-space variant in production sheet
    "Egypt": "EGY",
    "Equatorial Guinea": "GNQ",
    "Gabon": "GAB",
    "Libya": "LBY",
    "Nigeria": "NGA",
    "South Sudan": "SSD",
    "Sudan": "SDN",
    "Tunisia": "TUN",
    # Asia Pacific
    "Australia": "AUS",
    "Brunei": "BRN",
    "China": "CHN",
    "India": "IND",
    "Indonesia": "IDN",
    "Malaysia": "MYS",
    "Thailand": "THA",
    "Vietnam": "VNM",
}

# Global Energy Monitor (extraction tracker, oil infrastructure tracker)
GEM_NAME_TO_ISO3: dict[str, str] = {
    # Single-country entries
    "Algeria": "DZA",
    "Angola": "AGO",
    "Argentina": "ARG",
    "Australia": "AUS",
    "Austria": "AUT",
    "Azerbaijan": "AZE",
    "Bangladesh": "BGD",
    "Bolivia": "BOL",
    "Brazil": "BRA",
    "Brunei": "BRN",
    "Canada": "CAN",
    "Chad": "TCD",
    "China": "CHN",
    "Colombia": "COL",
    "Cuba": "CUB",
    "Cyprus": "CYP",
    "Côte d'Ivoire": "CIV",
    "Denmark": "DNK",
    "Ecuador": "ECU",
    "Egypt": "EGY",
    "Ethiopia": "ETH",
    "France": "FRA",
    "Germany": "DEU",
    "Ghana": "GHA",
    "Guatemala": "GTM",
    "Guyana": "GUY",
    "Hungary": "HUN",
    "India": "IND",
    "Indonesia": "IDN",
    "Iran": "IRN",
    "Iraq": "IRQ",
    "Ireland": "IRL",
    "Israel": "ISR",
    "Italy": "ITA",
    "Jamaica": "JAM",
    "Kazakhstan": "KAZ",
    "Kenya": "KEN",
    "Kuwait": "KWT",
    "Libya": "LBY",
    "Malaysia": "MYS",
    "Mauritania": "MRT",
    "Mexico": "MEX",
    "Morocco": "MAR",
    "Mozambique": "MOZ",
    "Myanmar": "MMR",
    "Namibia": "NAM",
    "Netherlands": "NLD",
    "Nigeria": "NGA",
    "Norway": "NOR",
    "Oman": "OMN",
    "Pakistan": "PAK",
    "Papua New Guinea": "PNG",
    "Peru": "PER",
    "Poland": "POL",
    "Qatar": "QAT",
    "Romania": "ROU",
    "Russia": "RUS",
    "Saudi Arabia": "SAU",
    "Senegal": "SEN",
    "South Africa": "ZAF",
    "South Sudan": "SSD",
    "Tanzania": "TZA",
    "Thailand": "THA",
    "Timor-Leste": "TLS",
    "Trinidad and Tobago": "TTO",
    "Türkiye": "TUR",
    "Uganda": "UGA",
    "United Arab Emirates": "ARE",
    "United Kingdom": "GBR",
    "United States": "USA",
    "Venezuela": "VEN",
    "Vietnam": "VNM",
    # Additional countries (primarily needed for gas pipeline coverage)
    "Afghanistan": "AFG",
    "Albania": "ALB",
    "Armenia": "ARM",
    "Belarus": "BLR",
    "Belgium": "BEL",
    "Benin": "BEN",
    "Bulgaria": "BGR",
    "Chile": "CHL",
    "Croatia": "HRV",
    "Czech Republic": "CZE",
    "Dominican Republic": "DOM",
    "Estonia": "EST",
    "Finland": "FIN",
    "Georgia": "GEO",
    "Greece": "GRC",
    "Hong Kong": "HKG",
    "Japan": "JPN",
    "Jordan": "JOR",
    "Kyrgyzstan": "KGZ",
    "Latvia": "LVA",
    "Lithuania": "LTU",
    "Luxembourg": "LUX",
    "Moldova": "MDA",
    "New Zealand": "NZL",
    "North Macedonia": "MKD",
    "Philippines": "PHL",
    "Portugal": "PRT",
    "Serbia": "SRB",
    "Singapore": "SGP",
    "Slovakia": "SVK",
    "Slovenia": "SVN",
    "Spain": "ESP",
    "Sweden": "SWE",
    "Switzerland": "CHE",
    "Syria": "SYR",
    "Taiwan": "TWN",
    "Tajikistan": "TJK",
    "Togo": "TGO",
    "Tunisia": "TUN",
    "Turkey": "TUR",
    "Turkmenistan": "TKM",
    "Ukraine": "UKR",
    "Uruguay": "URY",
    "Uzbekistan": "UZB",
    # Multi-country / disputed fields — assign to the geographically dominant
    # or first-named country for the purpose of heat-map aggregation.
    "Iran-Iraq": "IRN",
    "Iran-Saudi Arabia": "IRN",
    "Iran-United Arab Emirates": "IRN",
    "Kuwait-Saudi Arabia": "KWT",
    "Russia-Kazakhstan": "RUS",
    "Saudi Arabia-Iran": "SAU",
    "Senegal-Mauritania": "SEN",
    "Thailand-Malaysia": "THA",
    # Typo variants observed in GEM data
    "Kazkahstan": "KAZ",
    "Equatorial Guinea": "GNQ",
}


# NETL GOGI uses UN-style country names (ISO 3166-1 long form)
NETL_NAME_TO_ISO3: dict[str, str] = {
    "Afghanistan": "AFG",
    "Albania": "ALB",
    "Algeria": "DZA",
    "Angola": "AGO",
    "Antigua and Barbuda": "ATG",
    "Argentina": "ARG",
    "Armenia": "ARM",
    "Australia": "AUS",
    "Austria": "AUT",
    "Azerbaijan": "AZE",
    "Bahamas": "BHS",
    "Bahrain": "BHR",
    "Bangladesh": "BGD",
    "Barbados": "BRB",
    "Belarus": "BLR",
    "Belgium": "BEL",
    "Belize": "BLZ",
    "Benin": "BEN",
    "Bolivia (Plurinational State of)": "BOL",
    "Botswana": "BWA",
    "Brazil": "BRA",
    "Brunei Darussalam": "BRN",
    "Bulgaria": "BGR",
    "Burundi": "BDI",
    "Cabo Verde": "CPV",
    "Cambodia": "KHM",
    "Cameroon": "CMR",
    "Canada": "CAN",
    "Central African Republic": "CAF",
    "Chad": "TCD",
    "Chile": "CHL",
    "China": "CHN",
    "Colombia": "COL",
    "Comoros": "COM",
    "Costa Rica": "CRI",
    "Congo": "COG",
    "Cote D'Ivoire": "CIV",
    "Cote D''Ivoire": "CIV",  # double-apostrophe variant in NETL GeoJSON
    "Croatia": "HRV",
    "Cuba": "CUB",
    "Cyprus": "CYP",
    "Czech Republic": "CZE",
    "Democratic People's Republic of Korea": "PRK",
    "Democratic People''s Republic of Korea": "PRK",  # double-apostrophe variant
    "Democratic Republic of the Congo": "COD",
    "Denmark": "DNK",
    "Djibouti": "DJI",
    "Dominica": "DMA",
    "Dominican Republic": "DOM",
    "Ecuador": "ECU",
    "Egypt": "EGY",
    "El Salvador": "SLV",
    "Equatorial Guinea": "GNQ",
    "Eritrea": "ERI",
    "Estonia": "EST",
    "Ethiopia": "ETH",
    "Fiji": "FJI",
    "Finland": "FIN",
    "France": "FRA",
    "Gabon": "GAB",
    "Gambia (Republic of The)": "GMB",
    "Georgia": "GEO",
    "Germany": "DEU",
    "Ghana": "GHA",
    "Greece": "GRC",
    "Guatemala": "GTM",
    "Guinea": "GIN",
    "Guyana": "GUY",
    "Haiti": "HTI",
    "Honduras": "HND",
    "Hungary": "HUN",
    "Iceland": "ISL",
    "India": "IND",
    "Indonesia": "IDN",
    "Iran (Islamic Republic of)": "IRN",
    "Iraq": "IRQ",
    "Ireland": "IRL",
    "Israel": "ISR",
    "Italy": "ITA",
    "Jamaica": "JAM",
    "Japan": "JPN",
    "Jordan": "JOR",
    "Kazakhstan": "KAZ",
    "Kenya": "KEN",
    "Kuwait": "KWT",
    "Kyrgyzstan": "KGZ",
    "Lao People's Democratic Republic": "LAO",
    "Latvia": "LVA",
    "Lebanon": "LBN",
    "Lesotho": "LSO",
    "Libya": "LBY",
    "Lithuania": "LTU",
    "Luxembourg": "LUX",
    "Madagascar": "MDG",
    "Malawi": "MWI",
    "Malaysia": "MYS",
    "Malta": "MLT",
    "Mauritius": "MUS",
    "Mexico": "MEX",
    "Mongolia": "MNG",
    "Montenegro": "MNE",
    "Morocco": "MAR",
    "Mozambique": "MOZ",
    "Myanmar": "MMR",
    "Namibia": "NAM",
    "Nepal": "NPL",
    "Netherlands": "NLD",
    "New Zealand": "NZL",
    "Nicaragua": "NIC",
    "Nigeria": "NGA",
    "Norway": "NOR",
    "Oman": "OMN",
    "Pakistan": "PAK",
    "Panama": "PAN",
    "Papua New Guinea": "PNG",
    "Paraguay": "PRY",
    "Peru": "PER",
    "Philippines": "PHL",
    "Poland": "POL",
    "Portugal": "PRT",
    "Qatar": "QAT",
    "Republic of Korea": "KOR",
    "Republic of Moldova": "MDA",
    "Romania": "ROU",
    "Russian Federation": "RUS",
    "Saint Kitts and Nevis": "KNA",
    "Sao Tome and Principe": "STP",
    "Saudi Arabia": "SAU",
    "Senegal": "SEN",
    "Seychelles": "SYC",
    "Sierra Leone": "SLE",
    "Singapore": "SGP",
    "Slovakia": "SVK",
    "Slovenia": "SVN",
    "Solomon Islands": "SLB",
    "Somalia": "SOM",
    "South Africa": "ZAF",
    "South Sudan": "SSD",
    "Spain": "ESP",
    "Sri Lanka": "LKA",
    "Sudan": "SDN",
    "Sweden": "SWE",
    "Switzerland": "CHE",
    "Syrian Arab Republic": "SYR",
    "Thailand": "THA",
    "The Former Yugoslav Republic of Macedonia": "MKD",
    "Togo": "TGO",
    "Trinidad and Tobago": "TTO",
    "Tunisia": "TUN",
    "Turkey": "TUR",
    "Turkmenistan": "TKM",
    "Ukraine": "UKR",
    "United Arab Emirates": "ARE",
    "United Kingdom": "GBR",
    "United Republic of Tanzania": "TZA",
    "United States of America": "USA",
    "Uruguay": "URY",
    "Vanuatu": "VUT",
    "Venezuela": "VEN",  # short form when comma-split tokenizes the full name
    "Venezuela, Bolivarian Republic of": "VEN",
    "Viet Nam": "VNM",
    "Yemen": "YEM",
}


def lookup(name: str, source: str) -> str | None:
    """Return iso3 for a name; source in {'ei', 'gem', 'netl'}."""
    table = {"ei": EI_NAME_TO_ISO3, "gem": GEM_NAME_TO_ISO3, "netl": NETL_NAME_TO_ISO3}[source]
    return table.get(name) or table.get(name.strip())
