export type DataFormat = "parquet" | "geoparquet" | "json";

/** A span of time the rows actually cover (catalog version 7+). */
export interface CoverageSpan {
  /** Formatted to the grain: "1990", "2025-01", "2020-01-01". */
  readonly from: string;
  readonly through: string;
  readonly grain: "year" | "month" | "day";
  /** Only these layer tags; absent = every layer the entry feeds. */
  readonly layers?: readonly string[];
}

export interface CatalogEntry {
  readonly id: string;
  readonly label: string;
  readonly path: string;
  readonly format: DataFormat;
  readonly source_name: string;
  readonly source_url: string;
  readonly license: string;
  /** Always YYYY-MM-DD from catalog version 6 on (see scripts/transform/build_catalog.py). */
  readonly as_of: string;
  /** How often the publisher releases, from the source pin. */
  readonly cadence?: string;
  /**
   * What period the data describes, for time series. Differs from `as_of`
   * (release/retrieval date): EI's 2026 release has reserves through 2020.
   * Absent for snapshot tables, where `as_of` is the date.
   */
  readonly coverage?: readonly CoverageSpan[];
  readonly layers: readonly string[];
  /** Attribution string the source requires (GEM, LNG-T3, OSM …). */
  readonly attribution?: string;
  /** False for reproducibility artefacts no layer or scenario reads. */
  readonly runtime?: boolean;
  /**
   * Licence policy: these rows may be redistributed (CC BY 4.0, public domain,
   * or project-derived). Gates per-layer row export in the Share menu.
   */
  readonly redistributable?: boolean;
  /**
   * The file at `path` may be offered as-is on /data — every entry sharing it
   * is redistributable (false for assets.parquet: it mixes in ODbL rows).
   */
  readonly downloadable?: boolean;
  /** One-line reason a non-downloadable entry is view-only. */
  readonly download_note?: string;
  /** Rows this entry contributes (a subset when several sources share a file). */
  readonly rows?: number;
  /** Size of the file at `path`, in bytes. */
  readonly bytes?: number;
  /** Hex sha256 of the file at `path`. */
  readonly sha256?: string;
}

export interface Catalog {
  /** Schema version; >= 6 is generated by build_catalog.py. */
  readonly version: number;
  readonly generated_at: string;
  readonly entries: readonly CatalogEntry[];
}
