export type DataFormat = "parquet" | "geoparquet" | "json";

export interface CatalogEntry {
  readonly id: string;
  readonly label: string;
  readonly path: string;
  readonly format: DataFormat;
  readonly source_name: string;
  readonly source_url: string;
  readonly license: string;
  /** Always YYYY-MM-DD from catalog version 6 on (see scripts/transform/build_catalog.py). */
  readonly as_of: string;
  readonly layers: readonly string[];
  /** Attribution string the source requires (GEM, LNG-T3, OSM …). */
  readonly attribution?: string;
  /** False for reproducibility artefacts no layer or scenario reads. */
  readonly runtime?: boolean;
  /** Rows this entry contributes (a subset when several sources share a file). */
  readonly rows?: number;
  /** Size of the file at `path`, in bytes. */
  readonly bytes?: number;
  /** Hex sha256 of the file at `path`. */
  readonly sha256?: string;
}

export interface Catalog {
  /** Schema version; >= 6 is generated by build_catalog.py. */
  readonly version: number;
  readonly generated_at: string;
  readonly entries: readonly CatalogEntry[];
}
