"use client";
import { useEffect, useState } from "react";
import { GeoJsonLayer } from "@deck.gl/layers";
import type { Feature, FeatureCollection, Polygon, MultiPolygon } from "geojson";

export interface BasinProps extends Record<string, unknown> {
  basin_id: string;
  name: string | null;
  country_iso3: string | null;
  area_km2: number | null;
  region: string | null;
}

export type BasinFeature = Feature<Polygon | MultiPolygon, BasinProps>;
export type BasinCollection = FeatureCollection<Polygon | MultiPolygon, BasinProps>;

/**
 * Load basins.geojson sidecar (generated by build_basins.py).
 *
 * We deliberately fetch the GeoJSON sidecar instead of reading basins.parquet
 * via DuckDB-WASM + ST_AsGeoJSON because the spatial extension is not reliably
 * available in DuckDB-WASM dev builds (1.33.1-dev45.0). The GeoJSON path is
 * simpler, browser-native, and avoids extension lifecycle issues.
 */
// Cache the in-flight promise, not the resolved value, so callers mounting in
// the same tick share one fetch. Cleared on failure so a later call retries.
let _promise: Promise<BasinCollection> | undefined;

function loadBasins(): Promise<BasinCollection> {
  _promise ??= (async () => {
    const res = await fetch("/data/basins.geojson");
    if (!res.ok) throw new Error(`basins.geojson fetch failed: ${String(res.status)}`);
    return (await res.json()) as BasinCollection;
  })().catch((err: unknown) => {
    _promise = undefined;
    throw err;
  });
  return _promise;
}

/**
 * Returns a deck.gl GeoJsonLayer for basin polygons, or null when not visible.
 *
 * Color scheme:
 *   Fill:   muted brown, low alpha [120, 100, 80, 50]
 *   Stroke: same hue, higher alpha [120, 100, 80, 200]
 */
export function useBasinPolygonsLayer(visible: boolean): GeoJsonLayer | null {
  const [layer, setLayer] = useState<GeoJsonLayer | null>(null);

  useEffect(() => {
    const ctrl = { cancelled: false };
    if (!visible) {
      // Schedule the clear asynchronously so we never call setState synchronously
      // inside the effect body — avoids the react-hooks/set-state-in-effect lint rule.
      void Promise.resolve().then(() => {
        if (!ctrl.cancelled) setLayer(null);
      });
      return () => {
        ctrl.cancelled = true;
      };
    }
    void (async () => {
      try {
        const fc = await loadBasins();
        if (ctrl.cancelled) return;

        const l = new GeoJsonLayer<BasinProps>({
          id: "basins",
          data: fc,
          stroked: true,
          filled: true,
          getFillColor: [120, 100, 80, 50],
          getLineColor: [120, 100, 80, 200],
          lineWidthMinPixels: 0.5,
          pickable: true,
        });
        setLayer(l);
      } catch (err) {
        console.error("BasinPolygonsLayer load failed:", err);
      }
    })();
    return () => {
      ctrl.cancelled = true;
    };
  }, [visible]);

  return layer;
}
