"use client";
import { useEffect, useState } from "react";
import { GeoJsonLayer } from "@deck.gl/layers";
import type { Feature, FeatureCollection, LineString, MultiLineString } from "geojson";

export interface PipelineProps extends Record<string, unknown> {
  pipeline_id: string;
  name: string;
  status: string;
  commodity: string;
  capacity_kbpd: number | null;
  operator: string | null;
  start_year: number | null;
}

export type PipelineFeature = Feature<LineString | MultiLineString, PipelineProps>;
export type PipelineCollection = FeatureCollection<LineString | MultiLineString, PipelineProps>;

export interface PipelinesLayerInput {
  readonly visible: boolean;
  readonly commodityFilter?: "crude" | "gas"; // when set, only render features of this commodity
  readonly id?: string;                        // optional id override so we can mount two layers
}

/**
 * Load pipelines.geojson sidecar (generated by build_pipelines.py).
 *
 * We deliberately fetch the GeoJSON sidecar instead of reading pipelines.parquet
 * via DuckDB-WASM + ST_AsGeoJSON because the spatial extension is not reliably
 * available in DuckDB-WASM dev builds (1.33.1-dev45.0). The GeoJSON path is
 * simpler, browser-native, and avoids extension lifecycle issues.
 *
 * The cache holds ALL features. Per-instance commodity filtering happens after
 * the fetch, so two layers with different commodityFilter share a single fetch.
 */
let _cache: PipelineCollection | undefined;

async function loadPipelines(): Promise<PipelineCollection> {
  if (_cache) return _cache;
  const res = await fetch("/data/pipelines.geojson");
  if (!res.ok) throw new Error(`pipelines.geojson fetch failed: ${String(res.status)}`);
  _cache = (await res.json()) as PipelineCollection;
  return _cache;
}

/**
 * Returns a deck.gl GeoJsonLayer for pipelines (oil or gas), or null when not visible.
 *
 * Accepts either:
 *   - a bare boolean (back-compat with Phase 2 callers, treated as { visible })
 *   - a PipelinesLayerInput object with optional commodityFilter and id override
 *
 * Color scheme:
 *   Gas     operating       → teal,      alpha 220 (solid)
 *   Gas     in-construction → teal,      alpha 140 (translucent)
 *   Crude   operating       → navy blue, alpha 220 (solid)
 *   Crude   in-construction → navy blue, alpha 140 (translucent)
 * Opacity distinguishes status without a separate color, keeping the palette
 * consistent for analysts.
 */
export function usePipelinesLayer(input: PipelinesLayerInput | boolean): GeoJsonLayer | null {
  const cfg: PipelinesLayerInput =
    typeof input === "boolean" ? { visible: input } : input;
  const { visible, commodityFilter, id } = cfg;

  const [layer, setLayer] = useState<GeoJsonLayer | null>(null);

  useEffect(() => {
    const ctrl = { cancelled: false };
    if (!visible) {
      // Schedule the clear asynchronously so we never call setState synchronously
      // inside the effect body — avoids the react-hooks/set-state-in-effect lint rule.
      void Promise.resolve().then(() => {
        if (!ctrl.cancelled) setLayer(null);
      });
      return () => {
        ctrl.cancelled = true;
      };
    }
    void (async () => {
      try {
        const fc = await loadPipelines();
        if (ctrl.cancelled) return;

        // Filter features by commodity if requested; cache always holds all features.
        const features = commodityFilter
          ? fc.features.filter((f) => f.properties.commodity === commodityFilter)
          : fc.features;
        const filtered = { ...fc, features };

        const isGas = commodityFilter === "gas";
        const layerId =
          id ??
          (isGas
            ? "pipelines-gas"
            : commodityFilter === "crude"
            ? "pipelines-crude"
            : "pipelines");

        const l = new GeoJsonLayer<PipelineProps>({
          id: layerId,
          data: filtered,
          stroked: true,
          filled: false,
          lineWidthMinPixels: 1.2,
          getLineColor: (f) => {
            const operating = f.properties.status === "operating";
            if (isGas) {
              return operating ? [20, 140, 160, 220] : [20, 140, 160, 140];
            }
            return operating ? [40, 60, 120, 220] : [40, 60, 120, 140];
          },
          pickable: true,
        });
        setLayer(l);
      } catch (err) {
        console.error("PipelinesLayer load failed:", err);
      }
    })();
    return () => {
      ctrl.cancelled = true;
    };
  }, [visible, commodityFilter, id]);

  return layer;
}
