"use client";
import { useEffect, useState } from "react";
import { GeoJsonLayer } from "@deck.gl/layers";
import type { Feature, FeatureCollection, LineString, MultiLineString } from "geojson";

export interface PipelineProps extends Record<string, unknown> {
  pipeline_id: string;
  name: string;
  status: string;
  commodity: string;
  capacity_kbpd: number | null;
  operator: string | null;
  start_year: number | null;
}

export type PipelineFeature = Feature<LineString | MultiLineString, PipelineProps>;
export type PipelineCollection = FeatureCollection<LineString | MultiLineString, PipelineProps>;

/**
 * Load pipelines.geojson sidecar (generated by build_pipelines.py).
 *
 * We deliberately fetch the GeoJSON sidecar instead of reading pipelines.parquet
 * via DuckDB-WASM + ST_AsGeoJSON because the spatial extension is not reliably
 * available in DuckDB-WASM dev builds (1.33.1-dev45.0). The GeoJSON path is
 * simpler, browser-native, and avoids extension lifecycle issues.
 */
let _cache: PipelineCollection | undefined;

async function loadPipelines(): Promise<PipelineCollection> {
  if (_cache) return _cache;
  const res = await fetch("/data/pipelines.geojson");
  if (!res.ok) throw new Error(`pipelines.geojson fetch failed: ${String(res.status)}`);
  _cache = (await res.json()) as PipelineCollection;
  return _cache;
}

/**
 * Returns a deck.gl GeoJsonLayer for oil pipelines, or null when not visible.
 *
 * @param visible - controls whether the layer is loaded and returned.
 *
 * Color scheme:
 *   operating       → navy blue, alpha 220 (solid)
 *   in-construction → same hue, alpha 140 (translucent)
 * Opacity distinguishes status without a separate color, keeping the palette
 * consistent for analysts.
 */
export function usePipelinesLayer(visible: boolean): GeoJsonLayer | null {
  const [layer, setLayer] = useState<GeoJsonLayer | null>(null);

  useEffect(() => {
    const ctrl = { cancelled: false };
    if (!visible) {
      // Schedule the clear asynchronously so we never call setState synchronously
      // inside the effect body — avoids the react-hooks/set-state-in-effect lint rule.
      void Promise.resolve().then(() => {
        if (!ctrl.cancelled) setLayer(null);
      });
      return () => {
        ctrl.cancelled = true;
      };
    }
    void (async () => {
      try {
        const fc = await loadPipelines();
        if (ctrl.cancelled) return;

        const l = new GeoJsonLayer<PipelineProps>({
          id: "pipelines",
          data: fc,
          stroked: true,
          filled: false,
          lineWidthMinPixels: 1.2,
          getLineColor: (f) =>
            f.properties.status === "operating"
              ? [40, 60, 120, 220]
              : [40, 60, 120, 140],
          pickable: true,
        });
        setLayer(l);
      } catch (err) {
        console.error("PipelinesLayer load failed:", err);
      }
    })();
    return () => {
      ctrl.cancelled = true;
    };
  }, [visible]);

  return layer;
}
