import type { LayerKey } from "@/lib/symbology";
import { catalogEntriesFor } from "./sources";
import type { Catalog, CoverageSpan } from "@/lib/data-catalog/types";

/**
 * Per-layer data vintage for the "Data vintage" panel section and the "old"
 * marker on layer rows.
 *
 * Read from the bundled catalog rather than a hand-kept table, so it cannot
 * drift from the data the way TIME_AWARE_COVERAGE did after the 2026-09
 * refresh. `catalog.json` is regenerated by `build_all`, so a refreshed source
 * updates this with no code change.
 *
 * A layer is dated by when its data *ends*, not when its source was released:
 * the EI 2026 edition (as_of July 2026) carries reserves only through 2020,
 * and dating the reserves layer "Jul 2026" told users it was current. Time
 * series carry catalog `coverage`; snapshot tables (assets, pipelines, basins)
 * have none, and for them the snapshot date is the right answer.
 */
export interface LayerVintage {
  readonly key: LayerKey;
  readonly label: string;
  /** "series": dated by the last period its rows cover; "snapshot": by as_of. */
  readonly kind: "series" | "snapshot";
  /** Series only: last covered period at its grain ("2020", "2026-05", "2026-09-17"). */
  readonly through: string | null;
  readonly grain: CoverageSpan["grain"] | null;
  /** ISO date the data ends: last day of `through`, or the snapshot's as_of. */
  readonly dataEnd: string;
}

/** The catalog layer tag behind each toggle. */
const CATALOG_TAG: Readonly<Record<LayerKey, string>> = {
  reserves: "reserves",
  basins: "basins",
  extraction: "extraction",
  pipelines: "pipelines",
  refineries: "refineries",
  storage: "storage",
  ports: "ports",
  gas_pipelines: "gas_pipelines",
  lng_terminals: "lng_terminals",
  lng_voyages: "lng_voyages",
  gas_storage: "gas_storage",
  shale_regions: "shale_regions",
};

/**
 * Older than this and a layer is marked "old". 18 months, because every
 * layer's publisher releases at least annually (see `cadence`): data this old
 * is either a skipped refresh or a source that has stopped updating, which is
 * what a reader needs to know — EI reserves, frozen at 2020, is the latter.
 */
export const STALE_AFTER_MONTHS = 18;

/** Last calendar day of a period at its grain, as an ISO date. */
export function periodEnd(through: string, grain: CoverageSpan["grain"]): string {
  if (grain === "day") return through;
  if (grain === "year") return `${through}-12-31`;
  const [y, m] = through.split("-").map(Number);
  // Day 0 of the next month is the last day of this one.
  const last = new Date(Date.UTC(y ?? 0, m ?? 1, 0));
  return last.toISOString().slice(0, 10);
}

/**
 * When the layer's data ends.
 *
 * Several entries feed some layers (refineries = NETL topped up with OSM).
 * They are supplements rather than a blend, so the newest wins; reporting the
 * layer at NETL's date would understate how current it is. Where that matters,
 * the per-row tooltip cites the row's own source. Coverage spans win over
 * snapshot dates: the reserves layer is also tagged on countries.geojson,
 * whose boundary snapshot says nothing about how current the reserves are.
 */
export function layerVintage(
  key: LayerKey,
  label: string,
  catalog?: Catalog,
): LayerVintage | null {
  const tag = CATALOG_TAG[key];
  const entries = catalogEntriesFor(tag, catalog);
  let series: { span: CoverageSpan; end: string } | null = null;
  let snapshot: string | null = null;
  for (const e of entries) {
    const spans = (e.coverage ?? []).filter((s) => !s.layers || s.layers.includes(tag));
    for (const span of spans) {
      const end = periodEnd(span.through, span.grain);
      if (series === null || end > series.end) series = { span, end };
    }
    if (spans.length === 0 && (snapshot === null || e.as_of > snapshot)) snapshot = e.as_of;
  }
  if (series !== null) {
    return { key, label, kind: "series", through: series.span.through, grain: series.span.grain, dataEnd: series.end };
  }
  if (snapshot !== null) {
    return { key, label, kind: "snapshot", through: null, grain: null, dataEnd: snapshot };
  }
  return null;
}

/** Layers with a known vintage, most recent data first — the panel's order. */
export function layerVintages(
  labels: Readonly<Record<LayerKey, string>>,
  catalog?: Catalog,
): LayerVintage[] {
  const out: LayerVintage[] = [];
  for (const key of Object.keys(labels) as LayerKey[]) {
    const v = layerVintage(key, labels[key], catalog);
    if (v !== null) out.push(v);
  }
  return out.sort((a, b) => (a.dataEnd < b.dataEnd ? 1 : a.dataEnd > b.dataEnd ? -1 : 0));
}

/** Whole months from `dataEnd` to `today` (both ISO dates); never negative. */
export function monthsOld(dataEnd: string, today: string): number {
  const [ey, em, ed] = dataEnd.split("-").map(Number);
  const [ty, tm, td] = today.split("-").map(Number);
  const months = ((ty ?? 0) - (ey ?? 0)) * 12 + ((tm ?? 0) - (em ?? 0)) - ((td ?? 0) < (ed ?? 0) ? 1 : 0);
  return Math.max(0, months);
}

export function isStale(v: LayerVintage, today: string): boolean {
  return monthsOld(v.dataEnd, today) > STALE_AFTER_MONTHS;
}

/** "17 Sep 2026" — matches the gas-day format used in tooltips. */
export function formatAsOf(iso: string): string {
  const d = new Date(`${iso}T00:00:00Z`);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleDateString("en-GB", {
    day: "numeric",
    month: "short",
    year: "numeric",
    timeZone: "UTC",
  });
}

/** "to 2020" · "to May 2026" · "to 17 Sep 2026" · "as of 9 Apr 2025". */
export function formatVintage(v: LayerVintage): string {
  if (v.kind === "snapshot" || v.through === null || v.grain === null) return `as of ${formatAsOf(v.dataEnd)}`;
  return `to ${formatPeriod(v.through, v.grain)}`;
}

/** Hover text for the "old" marker: what is old, and by how much. */
export function staleNote(v: LayerVintage, today: string): string {
  const n = monthsOld(v.dataEnd, today);
  const what = v.kind === "series" ? `Data ends ${formatVintage(v).slice(3)}` : `Snapshot from ${formatAsOf(v.dataEnd)}`;
  return `${what}, ${n.toString()} months ago — older than the ${STALE_AFTER_MONTHS.toString()}-month mark.`;
}

function formatPeriod(value: string, grain: CoverageSpan["grain"]): string {
  if (grain === "year") return value;
  if (grain === "month") {
    const d = new Date(`${value}-01T00:00:00Z`);
    return d.toLocaleDateString("en-GB", { month: "short", year: "numeric", timeZone: "UTC" });
  }
  return formatAsOf(value);
}

/** "1990–2020" · "Jan 2025 – May 2026" · "1 Jan 2020 – 17 Sep 2026". */
export function formatSpan(span: CoverageSpan): string {
  const sep = span.grain === "year" ? "–" : " – ";
  return `${formatPeriod(span.from, span.grain)}${sep}${formatPeriod(span.through, span.grain)}`;
}
