import type { LayerKey } from "@/lib/symbology";
import { catalogEntriesFor } from "./sources";
import type { Catalog } from "@/lib/data-catalog/types";

/**
 * Per-layer data vintage for the "Data vintage" panel section.
 *
 * Read from the bundled catalog rather than a hand-kept table, so it cannot
 * drift from the data the way TIME_AWARE_COVERAGE did after the 2026-09
 * refresh. `catalog.json` is regenerated by `build_all`, so a refreshed source
 * updates this with no code change.
 */
export interface LayerVintage {
  readonly key: LayerKey;
  readonly label: string;
  /** ISO date, the newest as-of across the layer's catalog entries. */
  readonly asOf: string;
}

/** The catalog layer tag behind each toggle. */
const CATALOG_TAG: Readonly<Record<LayerKey, string>> = {
  reserves: "reserves",
  basins: "basins",
  extraction: "extraction",
  pipelines: "pipelines",
  refineries: "refineries",
  storage: "storage",
  ports: "ports",
  gas_pipelines: "gas_pipelines",
  lng_terminals: "lng_terminals",
  lng_voyages: "lng_voyages",
  gas_storage: "gas_storage",
};

/**
 * Newest as-of among a layer's catalog entries.
 *
 * Newest, not oldest, because these are supplements rather than a blend: the
 * refinery layer is NETL topped up with OpenStreetMap, and reporting it at
 * NETL's date would understate how current the layer is. Where that
 * distinction matters, the per-row tooltip cites the row's own source.
 */
export function layerAsOf(key: LayerKey, catalog?: Catalog): string | null {
  const entries = catalogEntriesFor(CATALOG_TAG[key], catalog);
  let newest: string | null = null;
  for (const e of entries) {
    if (newest === null || e.as_of > newest) newest = e.as_of;
  }
  return newest;
}

/** Layers with a known vintage, newest first — the panel's display order. */
export function layerVintages(
  labels: Readonly<Record<LayerKey, string>>,
  catalog?: Catalog,
): LayerVintage[] {
  const out: LayerVintage[] = [];
  for (const key of Object.keys(labels) as LayerKey[]) {
    const asOf = layerAsOf(key, catalog);
    if (asOf !== null) out.push({ key, label: labels[key], asOf });
  }
  return out.sort((a, b) => (a.asOf < b.asOf ? 1 : a.asOf > b.asOf ? -1 : 0));
}

/** "17 Sep 2026" — matches the gas-day format used in tooltips. */
export function formatAsOf(iso: string): string {
  const d = new Date(`${iso}T00:00:00Z`);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleDateString("en-GB", {
    day: "numeric",
    month: "short",
    year: "numeric",
    timeZone: "UTC",
  });
}
